.libPaths( c( .libPaths(), "~/userLibrary") )
library(affy)
args <- commandArgs(trailingOnly = TRUE)
data <- ReadAffy(filenames=args[1])
#eset.rma <- rma(data)
#write.exprs(eset.rma,file="test.rma.txt")
eset.mas5 <- mas5(data)
write.exprs(eset.mas5,file=args[2])
#exprSet.nologs = exprs(esets.mas5)
#exprSet <- log(exprSet.nologs,2)
#write.exprs(exprSet, file="GSE24080.mas5.log2.txt")
